[package]
name = "sp32-demo1"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"

[workspace]
members = ["price"]

[dependencies]
anyhow = "1.0"
log = "0.4"
esp-idf-svc = "0.53"
esp-idf-hal = "0.47"
mipidsi = "0.10"
embedded-graphics = "0.8"
embedded-hal = "1.0"
profont = "0.7"
price = { path = "price" }

[build-dependencies]
embuild = "0.33"

[profile.release]
opt-level = "s"
lto = "off"
