#!/usr/bin/env python3
"""Generate the e-paper logo bitmap (src/logo.rs) from the wireframe SVG asset.

The e-paper panel is 1-bit, so the color SVG is rasterized to a 35x35
monochrome bitmap (black disc, white glyph) and emitted as a Rust const array:
row-major, ceil(width/8) bytes per row, MSB first, 1 = black (drawn pixel).

Usage:
    .embuild/espressif/python_env/idf5.5_py3.12_env/bin/python scripts/convert-logo.py
"""

import io
import pathlib

import cairosvg
from PIL import Image

WIDTH = 35
HEIGHT = 35
# The rendered disc is orange (luma ~164) on white (255); anything clearly
# darker than white becomes a black pixel.
BLACK_THRESHOLD = 200
ROOT = pathlib.Path(__file__).resolve().parent.parent
SVG = ROOT / "wireframes" / "assets" / "bitcoin-logo.svg"
OUT = ROOT / "src" / "logo.rs"


def render() -> Image.Image:
    png = cairosvg.svg2png(
        url=str(SVG),
        output_width=WIDTH,
        output_height=HEIGHT,
        background_color="white",
    )
    return Image.open(io.BytesIO(png)).convert("L")


def to_bitmap(img: Image.Image) -> list[int]:
    bytes_per_row = (WIDTH + 7) // 8
    rows = []
    for y in range(HEIGHT):
        row = [0] * bytes_per_row
        for x in range(WIDTH):
            if img.getpixel((x, y)) < BLACK_THRESHOLD:  # black
                row[x // 8] |= 0x80 >> (x % 8)
        rows.extend(row)
    return rows


def main() -> None:
    img = render()
    bitmap = to_bitmap(img)

    preview = "\n".join(
        "".join("#" if img.getpixel((x, y)) < BLACK_THRESHOLD else "." for x in range(WIDTH))
        for y in range(HEIGHT)
    )
    print(preview)

    body = ", ".join(f"0x{b:02x}" for b in bitmap)
    OUT.write_text(
        f"""//! 1-bit Bitcoin logo for the e-paper frame ({WIDTH}x{HEIGHT}).
//!
//! Generated by `scripts/convert-logo.py` from
//! `wireframes/assets/bitcoin-logo.svg`. Do not edit by hand.
//!
//! Row-major, {(WIDTH + 7) // 8} bytes per row, MSB first; a set bit is a black pixel.

/// Logo width in pixels.
pub const LOGO_WIDTH: u32 = {WIDTH};
/// Logo height in pixels.
pub const LOGO_HEIGHT: u32 = {HEIGHT};
/// Bitmap data, `LOGO_WIDTH / 8 * LOGO_HEIGHT` bytes.
pub const LOGO_BITMAP: [u8; {len(bitmap)}] = [{body}];
"""
    )
    print(f"wrote {OUT} ({len(bitmap)} bytes)")


if __name__ == "__main__":
    main()
